#!/usr/bin/env zsh

# editor
export EDITOR="vim"
export VISUAL="vim"

export VIMINIT='let $MYVIMRC="$HOME/.config/vim/vimrc" | source $MYVIMRC'

# zsh
export ZDOTDIR="$HOME/.config/zsh"      # Location of zsh configs
export HISTFILE="$ZDOTDIR/.zsh_history" # History filepath
export HISTSIZE=2000                    # Maximum events for internal history
export SAVEHIST=2000                    # Maximum events in history file
export DIRSTACKSIZE=9                   # Maximum size of directory stack

# less
#   - set here so man also uses these settings
#   - custom man page colouring is possible if you wish to go down that road
#     of madness...
#     https://felipec.wordpress.com/2021/06/05/adventures-with-man-color/
#     https://wiki.archlinux.org/title/Color_output_in_console#less
LESS="--quit-if-one-screen "    # just display output if it fits on screen
LESS+="--ignore-case "          # smart case search
LESS+="--incsearch "            # search as you type
LESS+="--jump-target=.5 "       # current search result in middle of screen
LESS+="--LONG-PROMPT "          # more info on status line
LESS+="--RAW-CONTROL-CHARS "    # interpret colour control codes
LESS+="--squeeze-blank-lines "  # merge multiple blank lines
LESS+="--tabs=4 "               # 4 spaces for tabs
LESS+="--no-init "              # ignore termcap initialisation, in xterm this
                                # keeps last page on screen see:
                                # http://www.shallowsky.com/linux/noaltscreen.html
LESS+="--mouse "                # mouse support
LESS+="--wheel-lines=3 "        # mouse scroll speed
export LESS
export LESSHISTFILE="$HOME/.local/state/lesshst"

# PATH
# https://zsh.sourceforge.io/Guide/zshguide02.html#l24
typeset -U path
path+=($HOME/.local/bin)

# as required by zsh-autocomplete
skip_global_compinit=1

