# editors
if (( $+commands[nvim] )); then
    EDITOR="nvim"
else
    EDITOR="vim"
fi
export EDITOR
export VISUAL=$EDITOR
export SUDO_EDITOR=vim

# zsh
export ZDOTDIR="$HOME/.config/zsh"      # Location of zsh configs
ZSHSTATE="$HOME/.local/state/zsh"
if [[ ! -d $ZSHSTATE ]]; then
    command mkdir -p $ZSHSTATE
fi
HISTFILE="$ZSHSTATE/zsh_history" # History filepath
HISTSIZE=100000                  # Maximum events for internal history
SAVEHIST=$HISTSIZE               # Maximum events in history file
DIRSTACKSIZE=10                  # Maximum size of directory stack
KEYTIMEOUT=50                    # Wait time between multicharacter
                                 # keybinds (hundredths of seconds)

# less
#   - set here so man also uses these settings
#   - custom man page colouring is possible if you wish to go down that road
#     of madness...
#     https://felipec.wordpress.com/2021/06/05/adventures-with-man-color/
#     https://wiki.archlinux.org/title/Color_output_in_console#less
LESS="--ignore-case "          # smart case search
LESS+="--incsearch "           # search as you type
LESS+="--jump-target=.5 "      # current search result in middle of screen
LESS+="--LONG-PROMPT "         # more info on status line
LESS+="--RAW-CONTROL-CHARS "   # interpret colour control codes
LESS+="--squeeze-blank-lines " # merge multiple blank lines
LESS+="--tabs=4 "              # 4 spaces for tabs
LESS+="--mouse "               # mouse support
LESS+="--wheel-lines=3 "       # mouse scroll speed
LESS+="--hilite-search "       # only highlight last result from search
export LESS

# set filename to store history of less commands
export LESSHISTFILE="$HOME/.local/state/lesshst"
# keybinds for less, to set wrap around search by default
export LESSKEYIN="$HOME/.config/lesskey"
# set pre and post processors
export LESSOPEN="| lesspipe.sh %s"
export LESSCLOSE="lesspipe.sh %s %s"

# man
# align short man pages to top of screen and calculate file size when opening 
export MANPAGER="less --clear-screen --file-size"

# PATH
# https://zsh.sourceforge.io/Guide/zshguide02.html#l24
typeset -U path
path+=($HOME/.local/bin)

# docker
export DOCKER_CONFIG=$HOME/.config/docker

# rust
export CARGO_HOME=$HOME/.local/share/cargo
export RUSTUP_HOME=$HOME/.local/share/rustup
path+=($CARGO_HOME/bin)

# as required by zsh-autocomplete
skip_global_compinit=1

